#!/usr/bin/perl -w

# Convert awy.dat into SQL statements, see fg.sql for database definition

use strict;

my($sql) = "";
my($debug) = undef;

$debug = 1;

sub dprintf
{
    my($str) = @_;

    if($debug)
    {
        printf(STDERR $str);
    }
}

my($awy_id) = 1;

while(<STDIN>)
{
    my($line) = $_;

    if($line =~ /^$/)
    {
        next;
    }

    chomp($line);
    $line =~ s/^\s+//g;
    
    my($code);

    ($code) = ($line =~ m/^([^\s]+)/);

    if(!defined($code))
    {
        next;
    }

    if($code =~ /(\d+)/)
    {
        # end
    }
    elsif($code =~ /\S\S+/)
    {
        my($name_start, $lat_start, $lng_start,
            $name_end, $lat_end, $lng_end,
            $route, $base, $top, $seg_name) = split(/[ \t]+/, $line, 10);

        my($tmp);
        if($lng_start > $lng_end)
        {
            $tmp = $lng_start;
            $lng_start = $lng_end;
            $lng_end = $tmp;

            $tmp = $lat_start;
            $lat_start = $lat_end;
            $lat_end = $tmp;

            $tmp = $name_start;
            $name_start = $name_end;
            $name_end = $tmp;
        }

        my($rl, $rr, $rt, $rb);

        $rl = ($lng_start < $lng_end ? $lng_start : $lng_end);
        $rr = ($lng_start > $lng_end ? $lng_start : $lng_end);
        $rt = ($lat_start > $lat_end ? $lat_start : $lat_end);
        $rb = ($lat_start < $lat_end ? $lat_start : $lat_end);

        if($rl > $rr && $rr < 0)
        {
            # wrapped
            $rr += 360;
        }

        my($m, $b);

        if($lng_start == $lng_end)
        {
            $m = 'null';
            $b = 'null';
        }
        else
        {
            my($abslng_start, $abslng_end) = ($lng_start, $lng_end);
            $m = ($lat_end - $lat_start) / ($abslng_end - $abslng_start);
            $b = $lat_end - $m * $abslng_end;
        }

        $name_start =~ s/'/\\'/g;
        $name_end =~ s/'/\\'/g;
        $seg_name =~ s/'/\\'/g;

        $sql .= <<SQL;
INSERT INTO fg_awy
    (awy_id, name_start, lat_start, lng_start,
     name_end, lat_end, lng_end,
     m, b,
     rl, rr, rt, rb,
     enroute, base, top, seg_name)
    VALUES
    ($awy_id,
     '$name_start', $lat_start, $lng_start,
     '$name_end', $lat_end, $lng_end,
     $m, $b,
     $rl, $rr, $rt, $rb,
     $route, $base, $top, '$seg_name');
SQL

        $awy_id += 1;
    }
}

print($sql);

