#!/usr/bin/perl -w

# Convert awy.dat into SQL statements, see fg.sql for database definition

use strict;

my($sql) = "";
my($debug) = undef;

$debug = 1;

sub dprintf
{
    my($str) = @_;

    if($debug)
    {
        printf(STDERR $str);
    }
}

my($awy_id) = 1;

while(<STDIN>)
{
    my($line) = $_;

    if($line =~ /^$/)
    {
        next;
    }

    chomp($line);
    $line =~ s/^\s+//g;
    
    my($code);

    ($code) = ($line =~ m/^([^\s]+)/);

    if(!defined($code))
    {
        next;
    }

    if($code =~ /(\d+)/)
    {
        # end
    }
    elsif($code =~ /\S\S+/)
    {
        my($name_start, $lat_start, $lng_start,
            $name_end, $lat_end, $lng_end,
            $route, $base, $top, $seg_name) = split(/[ \t]+/, $line, 10);

        my($abslng_start, $abslng_end) = ($lng_start, $lng_end);
        
        if($abslng_start < 0)
        {
            $abslng_start += 360;
        }

        if($abslng_end < 0)
        {
            $abslng_end += 360;
        }

        my($m, $b);

        if($abslng_start == $abslng_end)
        {
            $m = 'null';
            $b = 'null';
        }
        else
        {
            $m = ($lat_end - $lat_start) / ($abslng_end - $abslng_start);
            $b = $lat_end - $m * $abslng_end;
        }

        $name_start =~ s/'/\\'/g;
        $name_end =~ s/'/\\'/g;
        $seg_name =~ s/'/\\'/g;

        $sql .= <<SQL;
INSERT INTO fg_awy
    (awy_id, name_start, lat_start, lng_start, abslng_start,
     name_end, lat_end, lng_end, abslng_end,
     m, b,
     enroute, base, top, seg_name)
    VALUES
    ($awy_id, '$name_start', $lat_start, $lng_start, $abslng_start,
     '$name_end', $lat_end, $lng_end, $abslng_end,
     $m, $b,
     $route, $base, $top, '$seg_name');
SQL

        $awy_id += 1;
    }
}

print($sql);

